# Create a Subset of the Data for Testing

This notebook loads in the combined_cleaned_group_crash.csv from an s3 bucket and then takes a subset of the data containing all crashes in four regions. This original data contained 2,884,080 crashes so the regions subsets were defined for simple local development of functions and modules.

The results were written to an s3 bucket called `{region}_crash_data.csv` and a local CSV file store in the `data/` folder with the same naming convention.

**Four Subset Regions:**

1. Boerne, TX: 3,111 crashes
2. Downtown San Antonio, TX: 4,326 crashes
3. Sugarland, TX: 20,046 crashes
4. Downtown Austin, TX: 4,326 crashes

**Warning**

The dataset is approximately 1.3 GB and it takes a long time to load all the data into a df on my local machine

In [1]:
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
from pathlib import Path
import sys
from pyspark.sql.types import StructType, StructField, StringType

# get root directory of project
ROOT_DIR = Path.cwd().parent

# Add the root directory to sys.path
sys.path.append(str(ROOT_DIR))

from src import spark_clustering
import config

DATA_DIR = ROOT_DIR / 'data'
print(f"DATA_DIR: {DATA_DIR}")

# Initialize Spark session
conf = SparkConf().setAppName("CrashDataProcessor").setMaster("local")
sc = SparkContext(conf=conf)
spark = SparkSession.builder.appName("CrashDataProcessor").getOrCreate()

DATA_DIR: /home/jovyan/Final_Project/data

**Read in the Crash Data**

In [4]:
# this function is for subset data testing
s3_url = 's3://txdot-crash-data-rice/raw-data/combined_cleaned_group_crash.csv'
crash_data = spark_clustering.read_crash_data(spark, s3_url)

In [5]:
crash_data.regions_df.take(1)

[Row(0='15657177', 1='N', 2='06/02/2019', 3='32.28023063', 4='-97.74661628', 5='0', 6='0', 7='0', 8='0', 9='1', 10='0', 11='0')]

**Columns**

See what columns exist in the dataset...

## Create Regions

I am going to create 4 small regions to test the clustering model on:

1. Boerne, TX
2. Downtown San Antonio, TX
3. Sugarland, TX
4. Midland, TX

**Boerne, TX**

In [5]:
lat_bounds = (29.7, 29.8)  # example latitude range
long_bounds = (-98.8, -98.6)  # example longitude range
region_filename = 'boerne_crash_data.csv'

spark_clustering.create_region_csv(crash_data, lat_bounds, long_bounds, region_filename)

DataFrame saved to txdot-crash-data/boerne_crash_data.csv

,Crash_ID,Crash_Fatal_Fl,Cmv_Involv_Fl,Schl_Bus_Fl,Rr_Relat_Fl,Medical_Advisory_Fl,Amend_Supp_Fl,Active_School_Zone_Fl,Crash_Date,Crash_Time,...,Investigator_Narrative,Secondary_Crash_Fl,Rpt_Dir_Traffic,Rpt_Sec_Speed_Limit,Investigat_Time_Rwy_Clrd,Investigat_Time_Scn_Clrd,Investigat_Notify_Date,Investigat_Arrv_Date,Investigat_Date_Rwy_Clrd,Investigat_Date_Scn_Clrd
576,17031755,N,N,N,N,N,N,N,04/24/2019,08:17 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,17032188,N,N,N,N,N,N,N,04/25/2019,09:30 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
714,17032211,N,Y,N,N,N,N,N,04/25/2019,09:00 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,17032241,N,N,N,N,Y,N,N,04/24/2019,10:36 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4852,17039431,N,N,N,N,N,N,N,04/26/2019,08:57 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2871693,19700208,N,N,N,N,N,N,N,8/10/2023,8:55 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2873295,19701817,N,N,N,N,N,N,N,8/6/2023,11:00 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2882760,19711676,N,N,N,N,N,N,N,8/18/2023,2:01 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2882761,19711677,N,N,N,N,N,N,N,8/10/2023,2:30 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2884080,19713579,N,N,N,N,N,N,N,8/5/2023,11:43 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Downtown San Antonio, TX**

In [6]:
lat_bounds = (29.4, 29.45)  #  latitude range
long_bounds = (-98.5, -98.45)  #  longitude range
region_filename = 'north_san_antonio_crash_data.csv'

spark_clustering.create_region_csv(crash_data, lat_bounds, long_bounds, region_filename)

DataFrame saved to txdot-crash-data/north_san_antonio_crash_data.csv

,Crash_ID,Crash_Fatal_Fl,Cmv_Involv_Fl,Schl_Bus_Fl,Rr_Relat_Fl,Medical_Advisory_Fl,Amend_Supp_Fl,Active_School_Zone_Fl,Crash_Date,Crash_Time,...,Investigator_Narrative,Secondary_Crash_Fl,Rpt_Dir_Traffic,Rpt_Sec_Speed_Limit,Investigat_Time_Rwy_Clrd,Investigat_Time_Scn_Clrd,Investigat_Notify_Date,Investigat_Arrv_Date,Investigat_Date_Rwy_Clrd,Investigat_Date_Scn_Clrd
381,17030974,N,N,N,N,N,N,N,04/24/2019,07:00 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,17031991,N,N,N,N,N,N,N,04/24/2019,06:30 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,17032423,N,N,N,N,N,N,N,04/24/2019,08:30 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,17032586,N,N,N,N,N,N,N,04/24/2019,05:41 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1047,17032970,N,N,N,N,N,N,N,04/26/2019,02:54 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2890029,19734240,N,N,N,N,N,N,N,8/12/2023,4:55 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890107,19735273,N,N,N,N,N,N,N,8/16/2023,8:25 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890119,19735477,N,N,N,N,N,N,N,8/17/2023,8:51 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890328,19738863,N,N,N,N,N,N,N,8/16/2023,11:00 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890894,19749113,N,N,N,N,N,N,N,8/10/2023,8:49 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Sugarland, TX**

In [7]:
lat_bounds = (29.55, 29.65)  #  latitude range
long_bounds = (-95.7, -95.5)  #  longitude range
region_filename = 'sugarland_crash_data.csv'

spark_clustering.create_region_csv(crash_data, lat_bounds, long_bounds, region_filename)

DataFrame saved to txdot-crash-data/sugarland_crash_data.csv

,Crash_ID,Crash_Fatal_Fl,Cmv_Involv_Fl,Schl_Bus_Fl,Rr_Relat_Fl,Medical_Advisory_Fl,Amend_Supp_Fl,Active_School_Zone_Fl,Crash_Date,Crash_Time,...,Investigator_Narrative,Secondary_Crash_Fl,Rpt_Dir_Traffic,Rpt_Sec_Speed_Limit,Investigat_Time_Rwy_Clrd,Investigat_Time_Scn_Clrd,Investigat_Notify_Date,Investigat_Arrv_Date,Investigat_Date_Rwy_Clrd,Investigat_Date_Scn_Clrd
182,17030052,N,N,N,N,N,N,N,04/24/2019,08:03 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,17030918,N,N,N,N,N,N,N,04/24/2019,01:55 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,17031598,N,N,N,N,N,N,N,04/24/2019,09:14 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,17032854,N,N,N,N,N,N,N,04/25/2019,04:00 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1334,17033659,N,N,N,N,N,N,N,04/25/2019,03:12 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888974,19727636,N,N,N,N,N,N,N,8/17/2023,5:20 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2889351,19730377,N,N,N,N,N,N,N,8/18/2023,8:57 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2889750,19731594,N,N,N,N,N,N,N,8/4/2023,6:39 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2889982,19733825,N,N,N,N,N,N,N,8/16/2023,4:16 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890598,19742831,N,N,N,N,N,N,N,8/18/2023,3:50 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Downtown Austin, TX**

In [8]:
lat_bounds = (30.25, 30.35)  #  latitude range
long_bounds = (-97.73, -97.63)  #  longitude range
region_filename = 'austin_crash_data.csv'

spark_clustering.create_region_csv(crash_data, lat_bounds, long_bounds, region_filename)

DataFrame saved to txdot-crash-data/austin_crash_data.csv

,Crash_ID,Crash_Fatal_Fl,Cmv_Involv_Fl,Schl_Bus_Fl,Rr_Relat_Fl,Medical_Advisory_Fl,Amend_Supp_Fl,Active_School_Zone_Fl,Crash_Date,Crash_Time,...,Investigator_Narrative,Secondary_Crash_Fl,Rpt_Dir_Traffic,Rpt_Sec_Speed_Limit,Investigat_Time_Rwy_Clrd,Investigat_Time_Scn_Clrd,Investigat_Notify_Date,Investigat_Arrv_Date,Investigat_Date_Rwy_Clrd,Investigat_Date_Scn_Clrd
124,17029759,N,N,N,N,N,N,N,04/24/2019,12:21 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,17029763,N,N,N,N,N,N,N,04/24/2019,08:11 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,17029849,N,N,N,N,N,N,N,04/24/2019,09:35 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,17029851,N,Y,N,N,N,N,N,04/24/2019,10:35 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1044,17032955,N,N,N,N,N,Y,N,04/24/2019,11:56 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889930,19733143,N,N,N,N,N,N,N,8/13/2023,3:45 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890314,19738559,N,N,N,N,N,N,N,8/5/2023,11:23 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890350,19739194,N,N,N,N,N,N,N,8/4/2023,1:55 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890602,19742914,N,N,N,N,N,N,N,7/31/2023,7:16 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890715,19744988,N,N,N,N,N,N,N,7/28/2023,12:17 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN